version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  setup:
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
  test:
    steps:
      - run: npm run check

workflows:
  build:
    jobs:
      - setup
